import { useState, useEffect } from "react";
import md from "markdown-it";
import Head from "next/head";
import { useSupabaseClient } from "@supabase/auth-helpers-react";
import Layout from "../../../layout";

export default function Contacts({ id }) {
  const [contact, setContact] = useState(null);
  const supabase = useSupabaseClient();
  useEffect(() => {
    (async () => {
      let { data, error, status } = await supabase
        .from("contacts")
        .select(`firstname, lastname, email, message`)
        .eq("id", id)
        .single();
      setContact(data);
    })();
  }
, [id, supabase]);

//fonction delete

const deleteData = async () => {
  const { data, error } = await supabase

    .from('contacts')
    .delete()
    .eq('id', id)
    .single()
    .then(() => {
      window.location.href = "/admin/contacts";
    })
    .catch((error) => {
      console.log('error', error)
    })
}


  return (
    <>
    <Layout>
      <Head>
        <title>WebTech - Contact message</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="wt-title">View a contact message</h1>
      {contact && (
        <div className="overflow-hidden divide-y divide-zinc-700 shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
          <div className="bg-slate-50">
            <dl className="grid grid-cols-[auto_1fr] px-3 py-4 [&_dt]:italic [&_dt]:text-zinc-700 [&_dt]:pr-3">
              <dt>Name</dt>
              <dd className="text-zinc-900">
                {contact.lastname}, {contact.firstname}
              </dd>
              <dt>Email</dt>
              <dd className="text-zinc-900">
                {contact.email}</dd>
            </dl>
          </div>
          <div className="px-3 py-10">
            <div
              dangerouslySetInnerHTML={{ __html: md().render(contact.message) }}
            />
          </div>
        </div>
      )}

      <button className="btn btn-primary"  onClick={deleteData}>Delete</button>
      </Layout>
    </>
  );
}

export async function getServerSideProps(context) {
  console.log(context.params);
  return {
    props: {
      id: context.params.id,
    },
  };
}
