import { useState } from "react";
import { useSupabaseClient } from "@supabase/auth-helpers-react";
import Head from "next/head";
import Layout from "../layout";
import UserContext from "../components/UserContext";
import { useContext } from "react";

export default function Commentaires() {
  const { user } = useContext(UserContext);
  const supabase = useSupabaseClient();
  const [message, setMessage] = useState(null);
  const onSubmit = async function (e) {
    e.preventDefault();
    const data = new FormData(e.target);
    const { error } = await supabase
      .from("contacts")
      .insert(Object.fromEntries(data), { returning: "minimal" });
    if (error) {
      setMessage("Sorry, an unexpected error occured.");
    } else {
      setMessage(
        <div>
          <h2 className="text-center mt-3">Confirmation</h2>
          <p>Thank you for contacting us. We will get back to you promptly.</p>
        </div>
      );
    }
  };
  return (
    <Layout>
      <Head>
        <title>WebTech - contact us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="wt-title">Envoie moi un commentaire :</h1>

      <form className="[&_span]:block grid gap-3 mt-4 mb-8 w-full max-w-[30rem] mx-auto text-slate-500 text-sm font-medium tracking-wide leading-6 space-y-4 sm:space-y-0 sm:grid-cols-2 sm:gap-6 sm:items-start sm:text-base" onSubmit={onSubmit}>
        <div>
          <label>
            <span>First name</span>
            <input type="text" name="firstname" />
          </label>
        </div>
        <div>
          <label>
            <span>Last name</span>
            <input type="text" name="lastname" />
          </label>
        </div>
        <div>
          <label>
            <span>Email</span>
            <input type="text" name="email" />
          </label>
        </div>
        <div>
          <label>
            <span>Message</span>
            <textarea name="message" />
          </label>
        </div>
        <div>
          <button className="rounded py-1 px-3 text-white bg-slate-500 hover:bg-blue-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" type="submit">
            Send
          </button>
        </div>
      </form>
      {message && (
        <div
          aria-label="Overlow below the drawer dialog"
          className="fixed inset-0 bg-black/80 flex items-center justify-center"
          onClick={() => setMessage(null)}
          role="dialog"
        >
          <div
            aria-label="Alert pane"
            className="max-h-[90vh] max-w-[95vw] overflow-auto p-4 prose bg-white"
          >
            {message}
          </div>
        </div>
      )}
      <br />
      <h3 className="wt-title mt-4 mb-2 text-center text-2xl font-bold tracking-wide leading-7 text-white-900 sm:text-3xl sm:truncate">Mon email :</h3>

      <p className="text-center font-bold tracking-wide  text-white-900 sm:truncate hover:text-blue-500">
        <a href="mailto:{user?.email}">{user?.email}</a>
      </p>
    </Layout>
  );
}
