import { useRouter } from "next/router";
import { useContext, useEffect } from "react";
import Head from "next/head";
import Layout from "../layout";
import UserContext from "../components/UserContext";
import Avatar from "../components/Avatar";
import Profile from "../components/profiles/profileuser";

export default function Contact() {
  const { user, logout, loading } = useContext(UserContext);
  const router = useRouter();

  useEffect(() => {
    if (!(user || loading)) {
      router.push("/login");
    }
  }, [user, loading, router]);
  const onClickLogout = function () {
    logout();
  };

  return (
    <Layout>
      <Head>
        <title>WebTech - user signedin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!(user || loading) ? (
        <p>Redirecting...</p>
      ) : (
        <>
          <Profile id={user.id} />


          <h2 className="flex text-justify p-4">Pour vous deconnecter: </h2>

          <button
            className="rounded px-3 py-2 text-white bg-slate-500 hover:bg-blue-500"
            onClick={onClickLogout}
          >
            Logout
          </button>
        </>
      )}
    </Layout>
  );
}
