import { useState } from "react";
import { useSupabaseClient } from "@supabase/auth-helpers-react";
import Head from "next/head";
import Layout from "../../layout";
import UserContext from "../../components/UserContext";
import { useContext } from "react";
import { useRouter } from "next/router";

export default function CreaArticle() {
  const router = useRouter();
  const { user } = useContext(UserContext);
  const supabase = useSupabaseClient();
  const [message, setMessage] = useState(null);
  const [annule, setAnnule] = useState(false);

  const onSubmit = async function (e) {
    e.preventDefault();
    const data = new FormData(e.target);
    if(annule === true){
            alert("Votre article est annule");
            router.push("/sheets");
    }
    else {
    const { error } = await supabase.from("articles").insert([
      {
        titre: data.get("titre"),
        contenu: data.get("contenu"),
        auteur: data.get("auteur"),
        user_id: user.id,
      },
    ]);

    if (error) {
      setMessage("Désolé, nous avons rencontre une erreur.");
    } else {
      setMessage(
        <div>
          <h2 className="text-center mt-3">Confirmation</h2>
          <p>
            Merci d avoir poste un article, nous vous recontacterons le plus
            vite possible
          </p>
        </div>
      );
      router.push("/sheets");
    }
  };
  };

  return (
    <Layout>
      <Head>
        <title>WebTech - Ecrire un article</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2
        className="wt-title text-center m-3
      "
      >
        Ecrire un article :{" "}
      </h2>

      <form onSubmit={onSubmit} className="flex flex-col items-center">
        <div class="w-full mb-4 border border-gray-200 rounded-lg bg-gray-50 dark:bg-gray-700 dark:border-gray-600">
          <div class="px-4 py-2 bg-white rounded-t-lg dark:bg-gray-800">
            <textarea
              id="contenu"
              name="contenu"
              rows="4"
              class="w-full px-0 text-sm text-gray-900 bg-white border-0 dark:bg-gray-800 focus:ring-0 dark:text-white dark:placeholder-gray-400"
              placeholder="Write an article..."
            ></textarea>
          </div>
          <div class="flex items-center justify-between px-3 py-2 border-t dark:border-gray-600">
            <div class="flex items-center space-x-2">
              <input
                type="text"
                name="titre"
                className="border border-gray-200 rounded-lg bg-gray-50 dark:bg-gray-700 dark:border-gray-600"
                placeholder="Titre"
              />
              <input
                type="text"
                name="auteur"
                className="border border-gray-200 rounded-lg bg-gray-50 dark:bg-gray-700 dark:border-gray-600"
                placeholder="Auteur"
              />
            </div>
            <button
              onClick={() => setAnnule(true)}
              class="inline-flex items-center py-2.5 px-4 text-xs font-medium text-center text-white bg-blue-700 rounded-lg focus:ring-4 focus:ring-blue-200 dark:focus:ring-blue-900 hover:bg-blue-800"
            >
              Cancel Article
            </button>
            <button 
            type="submit"
            class="inline-flex items-center py-2.5 px-4 text-xs font-medium text-center text-white bg-blue-700 rounded-lg focus:ring-4 focus:ring-blue-200 dark:focus:ring-blue-900 hover:bg-blue-800">
              Post Article
            </button>
          </div>
        </div>
      </form>

      {message && (
        <div
          aria-label="Overlow below the drawer dialog"
          className="fixed inset-0 bg-black/80 flex items-center justify-center"
          onClick={() => setMessage(null)}
          role="dialog"
        >
          <div
            aria-label="Alert pane"
            className="max-h-[90vh] max-w-[95vw] overflow-auto p-4 prose bg-white"
          >
            {message}
          </div>
        </div>
      )}
      <br />
    </Layout>
  );
}
